language: python
cache:
  pip: true
  ccache: true
git:
  depth: 3
env:
  global:
    - CIBW_BEFORE_BUILD='bash travis/cibw_before_build.sh'
    - CIBW_TEST_COMMAND='python {project}/test/test_smoke.py'
    - CIBW_ENVIRONMENT_LINUX=TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
script:
  - python -m pip install --upgrade pip wheel cibuildwheel
  - cibuildwheel --output-dir wheelhouse .
  # every maintainer wishing to do automatic release from the tag needs to setup
  # TWINE_USERNAME and TWINE_PASSWORD env vars on CI
  - |
    if [[ -n "${TRAVIS_TAG}" && -n "${TWINE_USERNAME}" ]]
    then
      python -m pip install --upgrade twine
      python -m twine upload --skip-existing wheelhouse/*.whl
    fi

matrix:
  include:
    - name: manylinux
      os: linux
      sudo: required
      services: docker
    - os: osx
      name: cp27-macosx
      language: shell
      install: HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio
      env: CIBW_BUILD='cp27-*'
    - os: osx
      name: cp37-macosx
      language: shell
      install: HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio
      env: CIBW_BUILD='cp37-*'
    # - os: osx
    #   name: cp36-macosx
    #   language: shell
    #   install: HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio
    #   env: CIBW_BUILD='cp36-*'
    # - os: osx
    #   name: cp35-macosx
    #   language: shell
    #   install: HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio
    #   env: CIBW_BUILD='cp35-*'
    # - os: osx
    #   name: cp34-macosx
    #   language: shell
    #   install: HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio
    #   env: CIBW_BUILD='cp34-*'
    # - os: windows
    #   name: cp27-win_amd64
    #   language: shell
    #   install:
    #     - choco install vcredist2008
    #     - choco install --ignore-dependencies vcpython27
    #     - ource travis/setup_python.windows.sh 2.7.16
    #   env: CIBW_PLATFORM=windows CIBW_BUILD='cp27-win_amd64'
    - os: windows
      name: cp35-win_amd64
      language: shell
      install: source travis/setup_cibuildwheel_env.windows.sh 3.5.4
    - os: windows
      name: cp36-win_amd64
      language: shell
      install: source travis/setup_cibuildwheel_env.windows.sh 3.6.8
    - os: windows
      name: cp37-win_amd64
      language: shell
      install: source travis/setup_cibuildwheel_env.windows.sh 3.7.4
