language: python
sudo: required
python:
  - '2.7'

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: CIBW_BEFORE_BUILD='/project/travis/build_deps.sh'
      install:
        - pip install cibuildwheel==0.7.0
      script:
        - cibuildwheel --output-dir dist
