env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-* cp36-manylinux1-i686 cp36-win32 cp36-win_amd64 cp36-macosx_*"
      CIBW_BEFORE_BUILD='travis/build_deps.sh'

language: python
sudo: required

matrix:
  include:
    - sudo: required
      services:
        - docker
      install:
        - pip install cibuildwheel==0.7.0

      script:
        - cibuildwheel --output-dir dist
