env:
  global:
    - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-*"
      CIBW_BEFORE_BUILD='/project/travis/build_deps.sh'

language: python
sudo: required

matrix:
  include:
    - sudo: false
      services:
        - docker
      install:
        - pip install cibuildwheel==0.7.0
      script:
        - cibuildwheel --output-dir dist
