language: python
cache:
  pip: true
  ccache: true
git:
  depth: 3
env:
  global:
    - CIBW_BEFORE_BUILD='travis/install_deps.sh'
    - CIBW_TEST_COMMAND='python {project}/test/test_smoke.py'
script:
  - python -m pip install --upgrade pip wheel cibuildwheel
  - cibuildwheel --output-dir wheelhouse .
  # every maintainer wishing to do automatic release from the tag needs to setup
  # TWINE_USERNAME and TWINE_PASSWORD env vars on CI
  - |
    if [[ -n "${TRAVIS_TAG}" && -n "${TWINE_USERNAME}" ]]
    then
      python -m pip install --upgrade twine
      python -m twine upload --skip-existing wheelhouse/*.whl
    fi

matrix:
  include:
    - name: manylinux
      os: linux
      sudo: required
      services:
        - docker
    - os: osx
      name: cp27-macosx
      language: shell
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio ccache
        # TODO ccache breaks building of python extension, investigate this if you care
        # about using ccache
        # - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      env: CIBW_BUILD='cp27-*'
    - os: osx
      name: cp37-macosx
      language: shell
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio ccache
      env: CIBW_BUILD='cp37-*'
    # - os: windows
    #   name: cp27-win_amd64
    #   language: shell
    #   install:
    #     - choco install vcredist2008
    #     - choco install --ignore-dependencies vcpython27
    #     - choco install python2 --version=2.7.16 -y --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python27-x64'"
    #     - export PATH="/c/Python27-x64:/c/Python27-x64/Scripts:$PATH"
    #   env:
    #     - CIBW_BEFORE_BUILD=travis\\install_deps.cmd
    #     - CIBW_PLATFORM=windows
    #     - CIBW_BUILD='cp27-win_amd64'
    - os: windows
      name: cp35-win_amd64
      language: shell
      install:
        - choco install python3 --version=3.5.4 -y -m --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python35-x64'"
        - export PATH="/c/Python35-x64:/c/Python35-x64/Scripts:$PATH"
      env:
        - CIBW_BEFORE_BUILD=travis\\install_deps.cmd
        - CIBW_PLATFORM=windows
        - CIBW_BUILD='cp35-win_amd64'
    - os: windows
      name: cp36-win_amd64
      language: shell
      install:
        - choco install python3 --version=3.6.8 -y -m --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python36-x64'"
        - export PATH="/c/Python36-x64:/c/Python36-x64/Scripts:$PATH"
      env:
        - CIBW_BEFORE_BUILD=travis\\install_deps.cmd
        - CIBW_PLATFORM=windows
        - CIBW_BUILD='cp36-win_amd64'
    - os: windows
      name: cp37-win_amd64
      language: shell
      install:
        - choco install python3 --version=3.7.4 -y -m --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python37-x64'"
        - export PATH="/c/Python37-x64:/c/Python37-x64/Scripts:$PATH"
      env:
        - CIBW_BEFORE_BUILD=travis\\install_deps.cmd
        - CIBW_PLATFORM=windows
        - CIBW_BUILD='cp37-win_amd64'
