notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD bash /io/travis/build-wheels.sh

before_deploy:
  - export RELEASE_PKG_FILE=$(ls /io/wheelhouse/*.whl)
  - echo "Files will be deployed to GitHub releases\n$RELEASE_PKG_FILE"

deploy:
  provider: releases
  api_key:
    secure: "Yw7bLpYSZjykOD7NnRHnaTD7DImUp12DSSK8QzF+wcOzfxnvEE1+5XxL9Sg68aSyCs7oo9CLFd3R93vc0cC1OB8SR/0rgk8bfRyxOFkufXQubsWV63/j1Z9Mfz3fs7d4tFHkPFA7SXocowFLrdEd27wF6ezR9eHVE5YfJCeaFoWRPUg+ji48Hr3Xj9+DhAyr0PEwQ784kStvUi8Bm+CutxK+k1qsZANVtasYs9omxoVEr4PQVe0iHEUD8E1yVaFmo8csYkltHpqccNH8tA71ZMNMvG4CCZFXgAiiTm7udarO2teMucKRCRnZtIIfWGd09CIIahBAHemXlHp7P27kLe88A5WosbgRrEfCSEDsA+H0e1mLXMT57uRgDnPrVmK+5XfRRhe2f2nT1MTThswRnimIeKl8Zth2+EnRDI3g+gyy4qGmDBhXus0NtRlIL/H/LUpVv2ZOTmGa5kIbtW+qtKM3HfsY/Cu4/4fPfRhsqjr6+ktamKcEqTzpQoYJwlBI2/73McXzM1ECxnliEB5eOnIHSd9CUn8Xpd9QPFl12t0iRpn4x2+AdqTk0qSBvazO0lCqmPHVhwg6xsmnuajW8ZZ94P0WWl9Qv39H4qCvOhA6xa4igIfpUt9QU23sIm0cIsf+8pMQN10/RrX5EarPvYBN9DIFIV+bpqqeJ/52DNY="
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: false
