language: python
sudo: required
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

matrix:
  include:
    - sudo: required
      services:
        - docker
      befor_build:
        - wget http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
        - tar -xzvf pa_stable_v19_20140130.tgz
        - cd portaudio
        - ./configure
        - make
        - sudo make install
        - cd ..
        - wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27.tar.gz
        - tar -xzvf libsndfile-1.0.27.tar.gz
        - cd libsndfile-1.0.27
        - ./configure 
        - make
        - sudo make install
        - cd ..
        - pip install -U --only-binary=numpy numpy

#    - os: osx
#      language: generic
#      env: PIP=pip2

script:
  - pip install -U cibuildwheel==0.7.0
  - cibuildwheel --output-dir wheelhouse