language: python
sudo: required
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: CIBW_BEFORE_BUILD='travis/build.deps.sh'
      install:
        - pip install cibuildwheel==0.7.0
      script:
        - cibuildwheel --output-dir dist
