env:
  global:
  # websockets only works on Python >= 3.4.
    - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-*"

language: python
sudo: required

matrix:
  include:
    - python: 2.7
      sudo: false
      services:
        - docker
      env: CIBW_BEFORE_BUILD='/project/travis/build_deps.sh'
      install:
        - pip install cibuildwheel==0.7.0
      script:
        - cibuildwheel --output-dir dist
