env:
  global:
    - CIBW_BEFORE_BUILD='travis/install_deps.sh'
    - CIBW_TEST_COMMAND='python {project}/test/test_smoke.py'

language: python
cache:
  - pip
  - ccache
sudo: required

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
    - os: osx
      language: generic
      env:
        - PIP=pip2
script:
  - $PIP install -U pip
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse .
