language: python
sudo: required

matrix:
  include:
    - python: 2.7
      sudo: false
      services:
        - docker
      env: CIBW_BEFORE_BUILD='/project/travis/build_deps.sh'
      install:
        - pip install cibuildwheel==0.7.0
      script:
        - cibuildwheel --output-dir dist
