language: python
cache:
  pip: true
  ccache: true
sudo: required
env:
  global:
    - CIBW_BEFORE_BUILD='travis/install_deps.sh'
    - CIBW_TEST_COMMAND='python {project}/test/test_smoke.py'
script:
  - python -m pip install --upgrade pip wheel cibuildwheel
  - cibuildwheel --output-dir wheelhouse .
  - if [[ "${TRAVIS_TAG:-}" != "" ]]; then
      python -m pip install --upgrade twine;
      python -m twine upload --skip-existing wheelhouse/*.whl;
    fi

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: shell
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio ccache
        # TODO ccache breaks building of python extension, investigate this if you care
        # about using ccache
        # - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - os: windows
      language: shell
      install:
         # XXX uncomment to enable python2.7
         #  - choco install vcredist2008
         #  - choco install --ignore-dependencies vcpython27
         #  - choco install python2 --version=2.7.16 -y --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python27-x64'"
         # XXX cibuildwheel on windows expects x64 Pythons to be in *-x64 dirs and fails if missing
         - choco install python3 --version=3.7.4 -y -m --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python37-x64'"
         - choco install python3 --version=3.6.8 -y -m --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python36-x64'"
         - choco install python3 --version=3.5.4 -y -m --override --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\\Python35-x64'"
         - export PATH="/c/Python37-x64:/c/Python37-x64/Scripts:$PATH"
      env:
        - CIBW_BEFORE_BUILD=travis\\install_deps.cmd
        - CIBW_PLATFORM=windows
        - CIBW_BUILD='cp37-win_amd64 cp36-win_amd64 cp35-win_amd64'
